services:
  bot:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - .env
    command: python -m src

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
